# Generated by Django 2.1.3 on 2018-11-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181117_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='hall',
            new_name='seance',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
