# Generated by Django 2.1.3 on 2018-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181117_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
